# Generated by Django 4.2.5 on 2023-09-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0000000', max_length=50)),
                ('address', models.CharField(default='0000000', max_length=100)),
                ('number', models.CharField(default='0000000', max_length=50)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=255)),
                ('username', models.CharField(default='0000000', max_length=50)),
                ('password', models.EmailField(default='000000', max_length=255)),
            ],
        ),
    ]
