# Generated by Django 4.2.5 on 2023-09-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_docdetails_patdetails_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='patdetails',
            name='doctor',
            field=models.CharField(default='aaa', max_length=100),
        ),
    ]
