# Generated by Django 4.2.5 on 2023-09-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_patdetails_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patdetails',
            name='doctor',
            field=models.CharField(default='aaa', max_length=200),
        ),
    ]
