# Generated by Django 4.2.5 on 2023-09-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_alter_patdetails_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patdetails',
            name='feedback',
            field=models.CharField(default='aaaaa', max_length=250),
        ),
    ]
