# Generated by Django 4.2.5 on 2023-09-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_patdetails_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='patdetails',
            name='age',
            field=models.CharField(default='0000000', max_length=50),
        ),
    ]
